const TYPES = {
    LOADING_DATA: 'LOADING_DATA',
    FETCH_DATA: 'FETCH_DATA',
    LOADED_DATA: 'LOADED_DATA',
    POST_REGIS: 'POST_REGIS',
    POST_LOGIN: 'POST_LOGIN',
    GET_CARS: "GET_CARS",
}

export default TYPES;